[source::...ta-cloudflare-dns*.log*]
sourcetype = tacloudflaredns:log

[source::...ta_cloudflare_dns*.log*]
sourcetype = tacloudflaredns:log

[cloudflare:dns]
AUTO_KV_JSON = 0
DATETIME_CONFIG = CURRENT
LINE_BREAKER = ([\r\n]+)
NO_BINARY_CHECK = 1
category = Splunk App Add-on Builder
description = Cloudflare DNS data dump
pulldown_type = 1

[cloudflare:zone]
AUTO_KV_JSON = 0
DATETIME_CONFIG = CURRENT
LINE_BREAKER = ([\r\n]+)
NO_BINARY_CHECK = 1
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
description = Cloudflare Zone data dump
pulldown_type = 1

