[source::...ta-cloudflare-dns*.log*]
sourcetype = tacloudflaredns:log

[source::...ta_cloudflare_dns*.log*]
sourcetype = tacloudflaredns:log

[cloudflare:dns]
DATETIME_CONFIG = CURRENT
INDEXED_EXTRACTIONS = json
LINE_BREAKER = ([\r\n]+)
NO_BINARY_CHECK = true
category = Splunk App Add-on Builder
description = Cloudflare DNS data dump
pulldown_type = 1

[cloudflare:zone]
DATETIME_CONFIG = CURRENT
INDEXED_EXTRACTIONS = json
LINE_BREAKER = ([\r\n]+)
NO_BINARY_CHECK = true
category = Splunk App Add-on Builder
description = Cloudflare Zone data dump
pulldown_type = 1

