
[admin:TA_cloudflare_dns]
match = /
members = TA_cloudflare_dns_settings, TA_cloudflare_dns_cloudflare_dns

[admin_external:TA_cloudflare_dns_settings]
handlertype = python
python.version = python3
handlerfile = TA_cloudflare_dns_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:TA_cloudflare_dns_cloudflare_dns]
handlertype = python
python.version = python3
handlerfile = TA_cloudflare_dns_rh_cloudflare_dns.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
