
[expose:TA_cloudflare_dns_settings]
pattern = TA_cloudflare_dns_settings
methods = POST, GET

[expose:TA_cloudflare_dns_settings_specified]
pattern = TA_cloudflare_dns_settings/*
methods = POST, GET, DELETE

[expose:TA_cloudflare_dns_cloudflare_dns]
pattern = TA_cloudflare_dns_cloudflare_dns
methods = POST, GET

[expose:TA_cloudflare_dns_cloudflare_dns_specified]
pattern = TA_cloudflare_dns_cloudflare_dns/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
